### ISSUE TITLE
Use OpenMP

### ISSUE THREAD

**Issue by jarad** [wlandau/fbseqOpenMP#1]
This should be easily parallelizable across multiple cores using OpenMP with a compiler directive such as 

```
#pragma omp parallel
for(i=0; i<n; i++) { ...
```

and the compiler flag

```
-fopenmp
```

Of course, then the package name will likely need to be changed.

**Comment by wlandau** [comment]
I thought it best to keep `fbseqSerial` the way it is and implement OpenMP support as a [separate backend package](https://github.com/wlandau/fbseqOpenMP), which is consistent with the system I had originally planned. I know this involves a lot of repeat code, but the alternative would be worse. OpenMP support has to be hard-coded into the package installation though [`Makevars`](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#OpenMP-support) and `#include <omp.h>`, which means we would lose portability. Linux and Windows would be fine since OpenMP is natively supported in the most current versions of `gcc`, but installing OpenMP for `clang` on a Mac would be real headache, and I might break the command line tools in the process.

**Comment by jarad** [comment]
The `laGP` package seems to have it figured out:

https://github.com/cran/laGP/blob/master/INSTALL

**Comment by wlandau** [comment]
Those installation instructions still say to manually edit the Makevars to toggle OpenMP support.

**Comment by wlandau** [comment]
Actually, the `_OPENMP` macro you mentioned solves our problem. Apparently, OpenMP automatically sets `_OPENMP`, so I used that to activate OpenMP without sacrificing portability. I also renamed this backend package to `fbseqOpenMP`.
