### ISSUE TITLE
Slice sampler for Horseshoe

### ISSUE THREAD

**Issue by jarad** [wlandau/fbseqOpenMP#2]
You may want to consider the horseshoe slice sampler in the `UpdateLambdaCPS_NEG` function in https://github.com/cran/monomvn/blob/master/src/hshoe.c

**Comment by wlandau** [comment]
I'm not 100% sure about everything that the code is doing, but I expanded my lit search, and I think Scott is using the technique at the beginning of Section 2.2 of his [2010 local-shrinkage paper](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwintOyakofNAhVFgj4KHRHKBpcQFggdMAA&url=http%3A%2F%2Farxiv.org%2Fabs%2F1010.5265&usg=AFQjCNE26wBAbzagMniqkGbI2GkjRu4hjg&sig2=1qIm8BikpAY3oOY35-s4zg), which is a special case of the main result by [Damien, Wakefield, and Walker (1999)](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwj3r6Kmk4fNAhUEdT4KHUu5BpYQFggkMAA&url=http%3A%2F%2Fdeepblue.lib.umich.edu%2Fbitstream%2Fhandle%2F2027.42%2F74035%2F1467-9868.00179.pdf%3Fsequence%3D1&usg=AFQjCNHvLGjItOYNKZJLJ1faDJbiw5D4uw&sig2=h5M3r3DxnVPEyB8myHcngw). The situation-specific slice sampler is pretty nifty, but I think the more important thing may be that the parameterization is different. Instead of sampling xi in [our model](https://github.com/wlandau/fbseqNotes/blob/master/models/h/h.pdf), they sample eta = 1/xi. The transformation alone may solve the problem because small values of eta may be numerically easier to deal with than enormous values of xi. 

The first thing I'll do is try sampling 1/xi using my own slice sampler. If that doesn't work, I'll switch to their slice sampler.

**Comment by wlandau** [comment]
I tried both options, and convergence with the horseshoe is still awful even though I am sampling from the correct full conditionals. The xi parameters have low Gelman factors, but I observe divergence just about everywhere else. Still, it was definitely worth a shot.
